ATMI++: atmi::Field Class Reference
atmi::Field Class Reference abstract
#include <Buffers.h>
Public Member Functions
virtual ~Field ()
int type ()
const char * tname ()
FLDID32 id ()
int number ()
const char * name ()
FLDOCC32 occurence ()
int error ()
virtual FLDLEN32 length ()=0
virtual long needed ()
const char * what ()
virtual Field & operator= (const string &)
Protected Member Functions
int handleFerror (int, const char *,...)
virtual void setFocc (FLDOCC32 occ)
virtual void setup (FLDID32 fid)
virtual int get (Buffer *b)=0
virtual int get (Buffer *b, FLDOCC32 occ)=0
virtual int add (Buffer *b)=0
virtual int set (Buffer *b)=0
virtual int remove (Buffer *b)
Friends
class Buffer
Detailed Description
Abstract class to manipulate a Field
Constructor & Destructor Documentation
virtual atmi::Field::~Field () inline virtual
Default destructor
Member Function Documentation
virtual int atmi::Field::add (Buffer * b) protected pure virtual
add the fiels into the buffer
When successfull the value of focc is set
Parameters
b buffer in which to add the field.
Implemented in atmi::TField< char * >, atmi::TField< string >, and atmi::TField< T >.
Referenced by atmi::Buffer::add().
int atmi::Field::error ()
Returns
the last Ferror32 value
virtual int atmi::Field::get (Buffer * b) protected pure virtual
Retrieves the value of the field found into the buffer
Parameters
b buffer from which to retrieve the field's value
Implemented in atmi::TField< char * >, atmi::TField< string >, and atmi::TField< T >.
Referenced by atmi::Buffer::get().
virtual int atmi::Field::get (Buffer * b, FLDOCC32 occ) protected pure virtual
Retrieves the value of the field's occurence found into the buffer
Upon success the value of focc is set to the retrieved occurence.
Parameters
b buffer from which to retrieve the field's value
occ occurence to retreive
Implemented in atmi::TField< char * >, atmi::TField< string >, and atmi::TField< T >.
int atmi::Field::handleFerror (int err, const char * msg, ...) protected
FLDID32 atmi::Field::id ()
Returns
the Field ID of the field
virtual FLDLEN32 atmi::Field::length () pure virtual
Returns
the length of the field's value
Implemented in atmi::TField< char * >, atmi::TField< string >, and atmi::TField< T >.
const char * atmi::Field::name ()
Returns
the name of the field
long atmi::Field::needed () virtual
int atmi::Field::number ()
Extracts the field number from the field identifier.
Returns
field number.
FLDOCC32 atmi::Field::occurence ()
Returns
the fields occurence (as last found in a buffer)
virtual Field& atmi::Field::operator= (const string &) inline virtual
Reimplemented in atmi::TField< string >.
int atmi::Field::remove (Buffer * b) protected virtual
removes the field from the buffer
Parameters
b the buffer from which to remove the field
Referenced by atmi::Buffer::remove().
virtual int atmi::Field::set (Buffer * b) protected pure virtual
set the value of the field's value
Parameters
b the buffer in which the value must be changed
Implemented in atmi::TField< char * >, atmi::TField< string >, and atmi::TField< T >.
Referenced by atmi::Buffer::set().
void atmi::Field::setFocc (FLDOCC32 occ) protected virtual
void atmi::Field::setup (FLDID32 fid) protected virtual
utility method to setup field's data
const char * atmi::Field::tname ()
Returns
the name of the fml field type
int atmi::Field::type ()
Possible values are: FLD_SHORT 0 short int FLD_LONG 1 long int FLD_CHAR 2 character FLD_FLOAT 3 single-precision float FLD_DOUBLE 4 double-precision float FLD_STRING 5 string - null terminated FLD_CARRAY 6 character array FLD_PTR 9 pointer to a buffer FLD_FML32 10 embedded FML32 buffer FLD_VIEW32 11 embedded VIEW32 buffer FLD_MBSTRING 12 multibyte character array
Returns
the field's type
const char * atmi::Field::what ()
Returns
a string describing the field
Friends And Related Function Documentation
friend class Buffer friend
The documentation for this class was generated from the following files:
include/Buffers.h
src/tuxedo/Field.cpp