ATMI++: atmi::Tuxedo Class Reference
atmi::Tuxedo Class Reference
#include <Tuxedo.h>
Public Member Functions
Tuxedo ()
virtual ~Tuxedo ()
char * allocate (const char *type, const char *subtype, long size)
char * extend (char *buffer, long extent)
void free (char *buffer)
int begin (int timeout=0)
int commit ()
int abort ()
long get_errno ()
const char * get_errmsg ()
int get_errnodetail ()
const char * get_errdetail ()
void set_context (TPCONTEXT_T c)
TPCONTEXT_T get_context ()
long get_flags ()
void set_flags (long flags)
void reset_flags (long flags)
void unsetFlags (long flags)
Static Public Member Functions
static const char * version ()
Static Public Attributes
static const long FAILED = -1
Protected Member Functions
void switch_context ()
void updateErrno ()
virtual int handleTperrno (int tpe, const char *msg=NULL,...)
Static Protected Member Functions
static long unset (long, long)
static long set (long, long)
Protected Attributes
long flags
nl_catd catd
Detailed Description
All common used ATMI method are group in this class.
Author
Herbert Koelman
Constructor & Destructor Documentation
atmi::Tuxedo::Tuxedo ()
atmi::Tuxedo::~Tuxedo () virtual
Member Function Documentation
int atmi::Tuxedo::abort ()
Abort XA transaction.
Return: Upon failure an TransactionException is raised.
References CATD_ATMI_SET.
Referenced by atmi::operator<<(), and atmi::operator>>().
char * atmi::Tuxedo::allocate (const char * type, const char * subtype, long size)
Allocate a new buffer of type. Depending on the type both subtype and len are optional.
Buffer types provided by Tuxedo CARRAY Character array (possibly containing NULL characters) that is neither encoded nor decoded during transmission STRING NULL-terminated character array FML FML fielded buffer VIEW C structure or FML view X_OCTET Equivalent to CARRAY; provided for XATMI compatibility X_C_TYPE Equivalent to VIEW; provided for XATMI compatibility X_ COMMON Equivalent to VIEW; provided for XATMI compatibility FML32 FML32 fielded buffer, using 32-bit identifiers and offsets VIEW32 C structure or FML32 view, using 32-bit identifiers, counter variables, and size variables XML Buffer for XML documents MBSTRING Character array for multibyte characters
Note that only the first eight bytes of type and the first 16 bytes of subtype are significant.
Parameters
type buffer type to allocate (STRING, VIEW, FML, ...)
subtype buffer subtype. NULL means none
size memory size to allocate.
Returns
allocated buffer or NULL if failed
Exceptions
TuxedotException if something goes wrong.
References CATD_ATMI_SET.
Referenced by atmi::Buffer::Buffer(), atmi::operator<<(), and atmi::operator>>().
int atmi::Tuxedo::begin (int timeout = 0)
Starts an XA transaction.
Parameters
timeout max duration in seconds for a transaction to complete.
Exceptions
TransactionException is raised upon failure.
References CATD_ATMI_SET.
Referenced by atmi::operator<<(), and atmi::operator>>().
int atmi::Tuxedo::commit ()
Commit XA transaction
Exceptions
TransactionException on failure.
References CATD_ATMI_SET.
Referenced by atmi::operator<<(), and atmi::operator>>().
char * atmi::Tuxedo::extend (char * buffer, long extent)
Routine to change the size of a typed buffer.
Parameters
buffer the buffer to resize (the return value maybe different)
extent number of bytes to add
Returns
reference to resized buffer
References CATD_ATMI_SET.
Referenced by atmi::Buffer::resize().
void atmi::Tuxedo::free (char * buffer)
Free a preveously allocated tuxedo buffer.
Referenced by atmi::operator<<(), atmi::operator>>(), and atmi::Buffer::~Buffer().
TPCONTEXT_T atmi::Tuxedo::get_context () inline
Returns
the current context
const char* atmi::Tuxedo::get_errdetail () inline
Returns
an error detail description string (if one exists).
const char* atmi::Tuxedo::get_errmsg () inline
Returns
an error description string of the last errno
long atmi::Tuxedo::get_errno () inline
Returns
the current errno value
int atmi::Tuxedo::get_errnodetail () inline
Returns
the current error detail (if one exist).
long atmi::Tuxedo::get_flags () inline
Returns
Tuxedo flags used by this instance.
int atmi::Tuxedo::handleTperrno (int tpe, const char * msg = NULL, ...) protected virtual
Triggers exceptions according to the given tperrno passed. The exception will be initialized with msg.
Parameters
tpe tperrno to handle
msg message to setup in thrown exception.
... substitution parameters
Returns
legacy will be removed when prototype will be changed to void handleTperrno()
References CATD_ATMI_SET, and atmi::Exception::setup_message().
void atmi::Tuxedo::reset_flags (long flags) inline
Reset flag value to TPNOFLAGS
long atmi::Tuxedo::set (long f, long sf) static protected
set bits in second argument in first argument
void atmi::Tuxedo::set_context (TPCONTEXT_T c) inline
set the Tuxedo context to use when calling Tuxedo functions.
When set, ATMI++ switches to this context (()@) before executing a Tuxedo call.
Parameters
c context to be used by this instance
void atmi::Tuxedo::set_flags (long flags) inline
Set some Tuxedo flags
void atmi::Tuxedo::switch_context () protected
If context is set (context != 0), then tpsetctxt is called. This method does nothing otherwise.
References CATD_ATMI_SET.
long atmi::Tuxedo::unset (long f, long uf) static protected
Unset bits in second argument from first argument
void atmi::Tuxedo::unsetFlags (long flags) inline
void atmi::Tuxedo::updateErrno () protected
static const char* atmi::Tuxedo::version () inline static
Returns
ATMI++ version number
References ATMI_VERSION.
Member Data Documentation
nl_catd atmi::Tuxedo::catd protected
const long atmi::Tuxedo::FAILED = -1 static
long atmi::Tuxedo::flags protected
The documentation for this class was generated from the following files:
include/Tuxedo.h
src/tuxedo/Tuxedo.cpp