ATMI++: atmi::Barrier Class Reference
atmi::Barrier Class Reference
#include <ThreadPool.h>
Public Member Functions
Barrier ()
~Barrier ()
void up ()
void down ()
void wait ()
unsigned int get_value () const
Detailed Description
A barrier (a rendez-vous point).
Some parallel computations need to "meet up" at certain points before continuing. This can be accomplished with with this classs.
Constructor & Destructor Documentation
atmi::Barrier::Barrier ()
constructor and destructor.
atmi::Barrier::~Barrier ()
Member Function Documentation
void atmi::Barrier::down ()
decrease the value
References atmi::Condition::broadcast().
Referenced by atmi::ThreadPool::barrier_remove_workers().
unsigned int atmi::Barrier::get_value () const inline
get the current size of the barrier.
Returns
the size of the barrier
Referenced by atmi::ThreadPool::get_current_workers(), atmi::ThreadPool::get_worker(), and atmi::ThreadPool::~ThreadPool().
void atmi::Barrier::up ()
increase the value.
Referenced by atmi::ThreadPool::barrier_add_workers().
void atmi::Barrier::wait ()
wait for the desactivation of the barrier.
References atmi::Condition::simple_wait().
Referenced by atmi::ThreadPool::~ThreadPool().
The documentation for this class was generated from the following files:
include/ThreadPool.h
src/utl/ThreadPool.cpp