ATMI++: atmi::Queue Class Reference
atmi::Queue Class Reference
#include <Tuxedo.h>
Public Member Functions
Queue (const char *qspace=NULL, const char *queue=NULL, const char *reply=NULL)
int enqueue (char *data, long len)
int dequeue (char **data, long *len)
int enqueue (Buffer *data)
int dequeue (Buffer *data)
int dequeueReply (char **data, long *len)
int dequeueReply (Buffer *data)
int enqueueReply (char *data, long len)
int enqueueReply (Buffer *data)
void set_reply_queue (const char *q)
const char * get_reply_queue ()
void set_queue_space (const char *qs)
const char * get_queue_space ()
void set_queue (char *q)
const char * get_queue ()
long get_qctl_flags ()
void set_message_wait (bool wait)
void setQWait (bool wait)
bool isQWaiting ()
bool is_message_waiting ()
void set_quality_of_service (long qos)
int get_diagno ()
void set_new_corrid ()
void unset_corrid ()
Public Member Functions inherited from atmi::Tuxedo
Tuxedo ()
virtual ~Tuxedo ()
char * allocate (const char *type, const char *subtype, long size)
char * extend (char *buffer, long extent)
void free (char *buffer)
int begin (int timeout=0)
int commit ()
int abort ()
long get_errno ()
const char * get_errmsg ()
int get_errnodetail ()
const char * get_errdetail ()
void set_context (TPCONTEXT_T c)
TPCONTEXT_T get_context ()
long get_flags ()
void set_flags (long flags)
void reset_flags (long flags)
void unsetFlags (long flags)
Protected Member Functions
int handleDiagnostics (int _tperrno, int _diagno, const char *msg,...)
Protected Member Functions inherited from atmi::Tuxedo
void switch_context ()
void updateErrno ()
virtual int handleTperrno (int tpe, const char *msg=NULL,...)
Additional Inherited Members
Static Public Member Functions inherited from atmi::Tuxedo
static const char * version ()
Static Public Attributes inherited from atmi::Tuxedo
static const long FAILED = -1
Static Protected Member Functions inherited from atmi::Tuxedo
static long unset (long, long)
static long set (long, long)
Protected Attributes inherited from atmi::Tuxedo
long flags
nl_catd catd
Detailed Description
Handles /Q operations
Constructor & Destructor Documentation
atmi::Queue::Queue (const char * qspace = NULL, const char * queue = NULL, const char * reply = NULL)
Creates an instance of Queue
Parameters
qspace qspace that handles the queue
queue the queue that will be manipulated
reply name of a reply
Member Function Documentation
int atmi::Queue::dequeue (char ** data, long * len)
dequeue a message
Parameters
data Tuxedo buffer (allocated with Tuxedo::allocate)
len length of the Tuxedo buffer
Referenced by atmi::operator<<().
int atmi::Queue::dequeue (Buffer * data)
dequeue a message
Parameters
data Tuxedo FML32 buffer (allocated with Tuxedo::allocate)
References atmi::Buffer::get_buffer(), and atmi::Buffer::set_buffer().
int atmi::Queue::dequeueReply (char ** data, long * len)
dequeue a reply message
Reply must have been set when Queue instance was created. If the flag TP TPQCORRID is set, then the correlation id value is used to retreive the message from the reply queue.
Parameters
data Tuxedo buffer (allocated with Tuxedo::allocate)
len length of the Tuxedo buffer
References CATD_ATMI_SET.
int atmi::Queue::dequeueReply (Buffer * data)
dequeue a reply message
Reply must have been set when Queue instance was created.
Parameters
data Tuxedo buffer (allocated with Tuxedo::allocate)
References atmi::Buffer::get_buffer().
int atmi::Queue::enqueue (char * data, long len)
enqueue a message
Parameters
data Tuxedo buffer (allocated with Tuxedo::allocate)
len length of the Tuxedo buffer
Referenced by atmi::operator>>().
int atmi::Queue::enqueue (Buffer * data)
enqueue a message
Parameters
data Tuxedo FML32 buffer (allocated with Tuxedo::allocate)
References atmi::Buffer::get_buffer().
int atmi::Queue::enqueueReply (char * data, long len)
enqueue a reply message
The reply queue is identified through the Qctl structure. It is responability of the caller to set the reply queue value to use.
Parameters
data Tuxedo buffer (allocated with Tuxedo::allocate)
len length of the Tuxedo buffer
References CATD_ATMI_SET.
int atmi::Queue::enqueueReply (Buffer * data)
enqueue a reply message
The reply queue is identified through the Qctl structure. It is responability of the caller to set the reply queue value to use.
Parameters
data Tuxedo buffer (allocated with Tuxedo::allocate)
References atmi::Buffer::get_buffer().
int atmi::Queue::get_diagno () inline
Returns
the diagnostic code returned by last call.
long atmi::Queue::get_qctl_flags () inline
Returns
the current value of QCTL flags
const char* atmi::Queue::get_queue () inline
const char* atmi::Queue::get_queue_space () inline
const char * atmi::Queue::get_reply_queue ()
Returns
current reply queue name
int atmi::Queue::handleDiagnostics (int _tperrno, int _diagno, const char * msg, ...) protected
References CATD_ATMI_SET, and atmi::Exception::setup_message().
bool atmi::Queue::is_message_waiting () inline
bool atmi::Queue::isQWaiting () inline
Check if QWait flag is set
Returns
true if wait flag is set
Deprecated:
use is_message_waiting instead
void atmi::Queue::set_message_wait (bool wait)
Wait until a message is enqueued.
Parameters
wait if true Queue waits for a message
void atmi::Queue::set_new_corrid ()
Calculate and set qctl corid
Correlation ID is made of pid+threadid+<current time="" in="" milliseconds>="">. When the correlation is set the flags TPQGETBYCORRID and TPQCORRID are also set. This means that subsequent calls to dequeue methods will get only message with the correleation id that was last set.
void atmi::Queue::set_quality_of_service (long qos)
Set the desired persistence mode (memory, disk, default) Accepted values are : TPQQOSDEFAULTPERSIST: uses the persistence mode defined with queue TPQQOSPERSISTENT: message are written onto persistent storage TPQQOSNONPERSISTENT: message are written into memory only (message are lost if the queue manager is interrupted)
Parameters
qos desired flags
References CATD_ATMI_SET.
void atmi::Queue::set_queue (char * q) inline
void atmi::Queue::set_queue_space (const char * qs) inline
Set the queuespace name to wich this queue associated.
Parameters
qs queue space name (32 characters max)
void atmi::Queue::set_reply_queue (const char * q)
indicate in wich queue the replies should be posted.
When called, QCTL flag TPQREPLYQ is set and the queue name passed os copied into replyqueue. If passed a NULL pointer, then the TPQREPLYQ flags is unset.
Parameters
q queue name
void atmi::Queue::setQWait (bool wait) inline
Deprecated:
use set_message_wait instead
void atmi::Queue::unset_corrid ()
Reset flags and value related to correlation id to off.
The documentation for this class was generated from the following files:
include/Tuxedo.h
src/tuxedo/Queue.cpp