ATMI++: atmi::Condition Class Reference
atmi::Condition Class Reference
#include <Concurrency.h>
Public Member Functions
int simple_wait ()
int wait (int millis=0)
int waitAndLock (int millis=0)
int signal ()
int broadcast ()
Condition ()
~Condition ()
Public Member Functions inherited from atmi::Mutex
int lock ()
int tryLock ()
int unlock ()
Mutex ()
~Mutex ()
Additional Inherited Members
Protected Attributes inherited from atmi::Mutex
pthread_mutex_t mutex
Constructor & Destructor Documentation
atmi::Condition::Condition ()
atmi::Condition::~Condition ()
Member Function Documentation
int atmi::Condition::broadcast ()
Referenced by atmi::Barrier::down().
int atmi::Condition::signal ()
Referenced by atmi::ThreadPool::add_worker_to_waiting_list(), atmi::Worker::set_job(), and atmi::Worker::stop().
int atmi::Condition::simple_wait ()
References atmi::Mutex::mutex.
Referenced by atmi::Worker::run(), and atmi::Barrier::wait().
int atmi::Condition::wait (int millis = 0)
References atmi::Mutex::unlock(), and waitAndLock().
int atmi::Condition::waitAndLock (int millis = 0)
References atmi::Mutex::lock(), and atmi::Mutex::mutex.
Referenced by wait().
The documentation for this class was generated from the following files:
include/Concurrency.h
src/utl/Condition.cpp