ATMI++: atmi::Mutex Class Reference
atmi::Mutex Class Reference
#include <Concurrency.h>
Public Member Functions
int lock ()
int tryLock ()
int unlock ()
Mutex ()
~Mutex ()
Protected Attributes
pthread_mutex_t mutex
Constructor & Destructor Documentation
atmi::Mutex::Mutex ()
atmi::Mutex::~Mutex ()
Member Function Documentation
int atmi::Mutex::lock ()
The mutex object is locked by calling pthread_mutex_lock. If the mutex is already locked, the calling thread blocks until the mutex becomes available. This operation returns with the mutex object referenced by mutex in the locked state with the calling thread as its owner.
Referenced by atmi::ScopedMutex::ScopedMutex(), and atmi::Condition::waitAndLock().
int atmi::Mutex::tryLock ()
The function pthread_mutex_trylock is identical to pthread_mutex_lock except that if the mutex object referenced by mutex is currently locked (by any thread, including the current thread), the call returns immediately.
int atmi::Mutex::unlock ()
The pthread_mutex_unlock function releases the mutex object referenced by mutex. The manner in which a mutex is released is dependent upon the mutex's type attribute. If there are threads blocked on the mutex object referenced by mutex when pthread_mutex_unlock is called, resulting in the mutex becoming available, the scheduling policy is used to determine which thread shall acquire the mutex. (In the case of PTHREAD_MUTEX_RECURSIVE mutexes, the mutex becomes available when the count reaches zero and the calling thread no longer has any locks on this mutex).
Referenced by atmi::Condition::wait(), and atmi::ScopedMutex::~ScopedMutex().
Member Data Documentation
pthread_mutex_t atmi::Mutex::mutex protected
Referenced by atmi::Condition::simple_wait(), and atmi::Condition::waitAndLock().
The documentation for this class was generated from the following files:
include/Concurrency.h
src/utl/Mutex.cpp