ATMI++: atmi::Worker Class Reference
atmi::Worker Class Reference
#include <ThreadPool.h>
Public Member Functions
Worker (ThreadPool *tp, std::string surname="", int destroy=0)
~Worker ()
bool is_working () const
virtual void run ()
void stop ()
void set_job (Runnable *)
Public Member Functions inherited from atmi::Thread
Thread (int destroy=0)
~Thread ()
int start ()
int join ()
int cancel ()
int getStatus ()
int destroy_when_ended ()
Protected Attributes
std::string surname
Runnable * Job
ThreadPool * pool
Condition s_cond
bool end_job
Detailed Description
This class define a worker. A worker is waiting for a job to arrive. When one job is assigned to the worker. The job is done. Once the job has been done, the worker add himself to the waiting list of the threadpool or, if it is a temporary worker, suicide to free the memory.
Constructor & Destructor Documentation
atmi::Worker::Worker (ThreadPool * tp, std::string surname = "", int destroy = 0)
constructors
Parameters
tp handle on threadpool owning the worker
surname name of worker.
destroy 1 if temporary worker 0 if permanent worker.
References atmi::ThreadPool::barrier_add_workers(), end_job, Job, pool, and surname.
atmi::Worker::~Worker ()
destructor
Member Function Documentation
bool atmi::Worker::is_working () const inline
accessors
Returns
true if worker is working, false if worker is not working.
void atmi::Worker::run () virtual
Main function call when the thread is starting
Reimplemented from atmi::Thread.
References atmi::ThreadPool::add_worker_to_waiting_list(), atmi::ThreadPool::barrier_remove_workers(), atmi::Thread::destroy_when_ended(), end_job, Job, pool, atmi::Runnable::run(), s_cond, and atmi::Condition::simple_wait().
void atmi::Worker::set_job (Runnable * job)
assign a job to the worker
Parameters
job job to assign to the worker.
References Job, s_cond, and atmi::Condition::signal().
Referenced by atmi::ThreadPool::do_job().
void atmi::Worker::stop ()
stop the execution of a permanent worker
References end_job, s_cond, and atmi::Condition::signal().
Member Data Documentation
bool atmi::Worker::end_job protected
ending condition
Referenced by run(), stop(), and Worker().
Runnable* atmi::Worker::Job protected
job assigne to the worker.
Referenced by run(), set_job(), and Worker().
ThreadPool* atmi::Worker::pool protected
ThreadPool owning this worker;
Referenced by run(), and Worker().
Condition atmi::Worker::s_cond protected
starting condition
Referenced by run(), set_job(), and stop().
std::string atmi::Worker::surname protected
Referenced by Worker().
The documentation for this class was generated from the following files:
include/ThreadPool.h
src/utl/Worker.cpp