ATMI++: atmi::Buffer Class Reference
atmi::Buffer Class Reference
#include <Buffers.h>
Public Member Functions
Buffer ()
Buffer (FBFR32 *b)
Buffer (FLDLEN32 len)
~Buffer ()
long size ()
long used ()
long unused ()
void pack ()
void extend ()
void resize (long extent)
Field * set (Field *f)
Field * add (Field *f)
Field * append (Field *f)
void remove (Field *f)
Field * get (Field *f)
Field * get (Field *f, FLDOCC32 occ)
long chksum ()
FLDOCC32 occurences (const Field *f)
FLDOCC32 num ()
void print ()
FBFR32 * get_buffer ()
void set_buffer (FBFR32 *b)
bool is_handling_memory ()
void set_handling_memory (bool b)
bool operator== (Buffer &)
Buffer & operator= (Buffer &)
Public Member Functions inherited from atmi::Tuxedo
Tuxedo ()
virtual ~Tuxedo ()
char * allocate (const char *type, const char *subtype, long size)
char * extend (char *buffer, long extent)
void free (char *buffer)
int begin (int timeout=0)
int commit ()
int abort ()
long get_errno ()
const char * get_errmsg ()
int get_errnodetail ()
const char * get_errdetail ()
void set_context (TPCONTEXT_T c)
TPCONTEXT_T get_context ()
long get_flags ()
void set_flags (long flags)
void reset_flags (long flags)
void unsetFlags (long flags)
Static Public Member Functions
static bool is_fml32_buffer (char *buffer)
Static Public Member Functions inherited from atmi::Tuxedo
static const char * version ()
Friends
class Field
Additional Inherited Members
Static Public Attributes inherited from atmi::Tuxedo
static const long FAILED = -1
Protected Member Functions inherited from atmi::Tuxedo
void switch_context ()
void updateErrno ()
virtual int handleTperrno (int tpe, const char *msg=NULL,...)
Static Protected Member Functions inherited from atmi::Tuxedo
static long unset (long, long)
static long set (long, long)
Protected Attributes inherited from atmi::Tuxedo
long flags
nl_catd catd
Detailed Description
FML Buffer
A fielded buffer is composed of Fields of fixed length (for example, TField<long>, TField<short>), and field for varying length fields (for example TField<string>).
Constructor & Destructor Documentation
atmi::Buffer::Buffer ()
Allocates a buffer of 1024bytes
References atmi::Tuxedo::allocate().
atmi::Buffer::Buffer (FBFR32 * b)
Create a new buffer reference.
Memory allocation (alloc/free) are not handled by the instance create by this constructor. We assume that the given buffer was allocated elsewhere. And it will be deallocated later.
Parameters
b set FML32 buffer reference
References set_buffer().
atmi::Buffer::Buffer (FLDLEN32 len)
Allocates a buffer of byte size.
Parameters
len bytes space of field value in bytres
References atmi::Tuxedo::allocate().
atmi::Buffer::~Buffer ()
default destructor
If memory was allocated by this instance then it will be freed. Otherwise the buffer is not deallocated.
References atmi::Tuxedo::free().
Member Function Documentation
Field * atmi::Buffer::add (Field * f)
Adds a field into the buffer
Parameters
f a pointer to the field to add into the buffer
Exceptions
BufferException upon failure
add the field into the buffer.
Parameters
f the field to add
References atmi::Field::add().
Field * atmi::Buffer::append (Field * f)
Appends a field to the buffer
Parameters
f a pointer to the field to add into the buffer
long atmi::Buffer::chksum ()
Returns
the current check sum of the buffer
Exceptions
BufferException when calcutaion fails.
Returns
the checksum value of the current buffer content
Referenced by operator==().
void atmi::Buffer::extend ()
Extends the buffer size with the given bytes
References resize(), and size().
Referenced by atmi::TField< T >::add(), atmi::TField< string >::add(), and atmi::TField< char * >::add().
Field * atmi::Buffer::get (Field * f)
Get the field value set in the buffer
Parameters
f the field to set
Returns
the field when set
Exceptions
BufferException upon failure
gets the value (if exsists) of passed field
Parameters
f field for which we want to get the value
References atmi::Field::get().
Field * atmi::Buffer::get (Field * f, FLDOCC32 occ)
Get the field value set in the buffer
Parameters
f the field to set
occ the field occurence to set
Returns
the field when set
Exceptions
BufferException upon failure
gets the value (if exsists) of passed field
Parameters
f field for which we want to get the value
References atmi::Field::get().
FBFR32 * atmi::Buffer::get_buffer ()
Returns
return FML32 buffer reference
the reference the current internal buffer.
Referenced by atmi::Tp::acall(), atmi::TField< T >::add(), atmi::TField< string >::add(), atmi::TField< char * >::add(), atmi::Tp::call(), atmi::Queue::dequeue(), atmi::Queue::dequeueReply(), atmi::Queue::enqueue(), atmi::Queue::enqueueReply(), atmi::TField< T >::get(), atmi::TField< string >::get(), atmi::TField< char * >::get(), atmi::Tp::reply(), atmi::TField< T >::set(), atmi::TField< string >::set(), and atmi::TField< char * >::set().
bool atmi::Buffer::is_fml32_buffer (char * buffer) inline static
Returns
true if it's a FMLTYPE32 buffer type
Exceptions
Exception if we failed to get buffer type (tptypes)
Referenced by set_buffer().
bool atmi::Buffer::is_handling_memory ()
Returns
true if this instance willfree allocated memory buffer.
FLDOCC32 atmi::Buffer::num ()
Returns
the number of fields into the buffer
return count of all occurrences in buffer
FLDOCC32 atmi::Buffer::occurences (const Field * f)
Returns
the number of occurences of the field into the buffer
returns the number of occurence of the given field into the buffer
Parameters
f a field for which to search for occurences
Referenced by atmi::TField< T >::add(), atmi::TField< string >::add(), and atmi::TField< char * >::add().
Buffer & atmi::Buffer::operator= (Buffer & b)
Copies the content of a fielded buffer into another
Copy's the content of one buffer into the other.
Parameters
b source buffer
Returns
target buffer
bool atmi::Buffer::operator== (Buffer & b)
Checks equality of two buffers (based upon chksum)
Returns
true if both checksums are equal.
true if both buffer's checksums were equal
References chksum().
void atmi::Buffer::pack ()
Removes unused space allocation
References resize(), and used().
void atmi::Buffer::print ()
print on stdout the content of the buffer. Mainly used for debugging
print's on stdout the content of the buffer (debugging purpose mainly)
void atmi::Buffer::remove (Field * f)
Removes the field from the buffer
Parameters
f a pointer to the field to remove
Exceptions
BufferException upon failure
remove a field from the buffer
Parameters
f field to remove
References atmi::Field::remove().
void atmi::Buffer::resize (long extent)
Extends the buffer size with the given bytes
Parameters
extent size in bytes of the extent
Exceptions
BufferException upon failure
References atmi::Tuxedo::extend().
Referenced by extend(), and pack().
Field * atmi::Buffer::set (Field * f)
Set a field's value into the buffer
Parameters
f a pointer to the field for which to change the value
Exceptions
BufferException upon failure
References atmi::Field::set().
void atmi::Buffer::set_buffer (FBFR32 * b)
Set a new buffer reference. Previous buffer is deallocated before assign the passed value.
Parameters
b set FML32 buffer reference
replaces the current buffer reference by the given one.
If preveous reference was allocated by this instance, then the buffer is freed before setting the new buffer reference. The buffer instance is then flagged as not allocated. Meaning that it's up to you to free the memory that was allocated.
Parameters
b reference of an FML buffer.
Exceptions
Exception if the buffer is not an FML buffer.
References is_fml32_buffer().
Referenced by Buffer(), atmi::Tp::call(), atmi::Queue::dequeue(), and atmi::Tp::reply().
void atmi::Buffer::set_handling_memory (bool b)
Parameters
b If true then destructor will free referenced buffer.
long atmi::Buffer::size ()
Returns
the size of the buffer (in bytes)
Referenced by atmi::Tp::acall(), atmi::TField< T >::add(), atmi::TField< string >::add(), atmi::TField< char * >::add(), atmi::Tp::call(), extend(), and atmi::Tp::reply().
long atmi::Buffer::unused ()
Returns
number of bytes not yet used into the buffer
long atmi::Buffer::used ()
Returns
number of bytes stored into the buffer
Referenced by atmi::TField< T >::add(), atmi::TField< string >::add(), atmi::TField< char * >::add(), and pack().
Friends And Related Function Documentation
friend class Field friend
The documentation for this class was generated from the following files:
include/Buffers.h
src/tuxedo/Buffer.cpp