ATMI++: atmi::Thread Class Reference
atmi::Thread Class Reference
#include <Thread.h>
Public Member Functions
Thread (int destroy=0)
~Thread ()
virtual void run ()
int start ()
int join ()
int cancel ()
int getStatus ()
int destroy_when_ended ()
Detailed Description
Handles POSIX (Portable Operating System Interface) threads.
class ReaderThread: public Thread { public: void run() {...} };
ReaderThread rt; rt.start();
Constructor & Destructor Documentation
atmi::Thread::Thread (int destroy = 0)
create a new thread
Parameters
destroy indicates that the thread should delete itself when ended.
atmi::Thread::~Thread ()
cleanup thread ressources.
Member Function Documentation
int atmi::Thread::cancel ()
The cancel subroutine requests the cancellation of the thread thread. The action depends on the cancelability of the target thread:
o If its cancelability is disabled, the cancellation request is set pending. o If its cancelability is deferred, the cancellation request is set pending till the thread reaches a cancellation point. o If its cancelability is asynchronous, the cancellation request is acted upon immediately; in some cases, it may result in unexpected behaviour.
The cancellation of a thread terminates it safely, using the same termination procedure as the pthread_exit subroutine.
int atmi::Thread::destroy_when_ended () inline
Referenced by atmi::Worker::run(), and atmi::ThreadStartup().
int atmi::Thread::getStatus () inline
int atmi::Thread::join ()
The join subroutine blocks the calling thread until the thread thread terminates. The target thread's termination status is returned in the status parameter.
If the target thread is already terminated, but not yet detached, the subroutine returns immediately. It is impossible to join a detached thread, even if it is not yet terminated. The target thread is automatically detached after all joined threads have been woken up.
This subroutine does not itself cause a thread to be terminated. It acts like the pthread_cond_wait subroutine to wait for a special condition.
void atmi::Thread::run () virtual
Override this operation with the code that the POSIX thread should run. It is actually called by the extern "C" function ThreadStartup which then calls the thread's run operation.
Implements atmi::Runnable.
Reimplemented in atmi::Worker.
Referenced by atmi::ThreadStartup().
int atmi::Thread::start ()
The start subroutine creates a new thread and initializes its attributes using the thread attributes object specified by the attr parameter. The new thread inherits its creating thread's signal mask; but any pending signal of the creating thread will be cleared for the new thread.
The new thread is made runnable, and will start executing the run routine, with.
After thread creation, the thread attributes object can be reused to create another thread, or deleted.
The thread terminates in the following cases:
o The thread returned from its starting routine (the main routine for the initial thread) o The thread called the pthread_exit subroutine o The thread was canceled o The thread received a signal that terminated it o The entire process is terminated due to a call to either the exec or exit subroutines.
Note: The pthread.h header file must be the first included file of each source file using the threads library. Otherwise, the -D_THREAD_SAFE compilation flag should be used, or the cc_r compiler used. In this case, the flag is automatically set.
When multiple threads are created in a process, the FULL_CORE flag is set for all signals. This means that if a core file is produced, it will be much bigger than a single_threaded application. This is necessary to debug multiple-threaded processes.
References atmi::ThreadStartup().
Referenced by atmi::ThreadPool::get_worker().
The documentation for this class was generated from the following files:
include/Thread.h
src/utl/Thread.cpp