ATMI++: atmi::ThreadPool Class Reference
atmi::ThreadPool Class Reference
#include <ThreadPool.h>
Public Member Functions
ThreadPool (unsigned int min, unsigned int max)
~ThreadPool ()
unsigned int get_max_workers () const
unsigned int get_permanent_workers () const
unsigned int get_current_workers () const
void add_worker_to_waiting_list (Worker *)
int do_job (Runnable *job)
void barrier_add_workers ()
void barrier_remove_workers ()
Protected Member Functions
Worker * get_worker ()
Protected Attributes
unsigned int number_of_permanent_workers
unsigned int max_concurrent_workers
std::vector< Worker * > workers_list
std::list< Worker * > waiting_workers
Condition update_cond
Barrier b_cond
Detailed Description
A ThreadPool runs jobs using pre-allocated threads. A job is submitted using ThreadPool.do_job method which selects an availbale thread and uses it to run the job.
When constructed the ThreadPool creates a minimum number of availbale threads. The ThreadPool will serve at most the max number of Threads (see ThreaPool constructor).
Author
eric belloni
Since
2.0
Constructor & Destructor Documentation
atmi::ThreadPool::ThreadPool (unsigned int min, unsigned int max)
constructor
Parameters
min number of threads that will be pre-allocated.
max maximum number of threads this instance will allow to run at one time.
References max_concurrent_workers, number_of_permanent_workers, and workers_list.
atmi::ThreadPool::~ThreadPool ()
destructor
References b_cond, atmi::Barrier::get_value(), number_of_permanent_workers, atmi::Barrier::wait(), and workers_list.
Member Function Documentation
void atmi::ThreadPool::add_worker_to_waiting_list (Worker * w)
add a worker to the waiting list
References atmi::Condition::signal(), update_cond, and waiting_workers.
Referenced by atmi::Worker::run().
void atmi::ThreadPool::barrier_add_workers ()
barrier management
References b_cond, and atmi::Barrier::up().
Referenced by atmi::Worker::Worker().
void atmi::ThreadPool::barrier_remove_workers ()
References b_cond, and atmi::Barrier::down().
Referenced by atmi::Worker::run().
int atmi::ThreadPool::do_job (Runnable * job)
Runs the given Runnable instance into an available Thread
Parameters
job a job to run
References get_worker(), and atmi::Worker::set_job().
unsigned int atmi::ThreadPool::get_current_workers () const inline
Returns
number of working workers.
References atmi::Barrier::get_value().
unsigned int atmi::ThreadPool::get_max_workers () const inline
accessors
Returns
number of maximum worker in threadpool.
References max_concurrent_workers.
unsigned int atmi::ThreadPool::get_permanent_workers () const inline
accessors
Returns
current number of permanent worker.
References number_of_permanent_workers.
Worker * atmi::ThreadPool::get_worker () protected
get handle on a waiting thread
Returns
handle on a waiting worker.
References b_cond, atmi::Barrier::get_value(), max_concurrent_workers, atmi::Thread::start(), update_cond, and waiting_workers.
Referenced by do_job().
Member Data Documentation
Barrier atmi::ThreadPool::b_cond protected
Referenced by barrier_add_workers(), barrier_remove_workers(), get_worker(), and ~ThreadPool().
unsigned int atmi::ThreadPool::max_concurrent_workers protected
Referenced by get_max_workers(), get_worker(), and ThreadPool().
unsigned int atmi::ThreadPool::number_of_permanent_workers protected
max thread in thread pool
Referenced by get_permanent_workers(), ThreadPool(), and ~ThreadPool().
Condition atmi::ThreadPool::update_cond protected
mutex to update waiting thread
Referenced by add_worker_to_waiting_list(), and get_worker().
std::list<Worker *> atmi::ThreadPool::waiting_workers protected
waiting thread
Referenced by add_worker_to_waiting_list(), and get_worker().
std::vector<Worker *> atmi::ThreadPool::workers_list protected
list of threads
Referenced by ThreadPool(), and ~ThreadPool().
The documentation for this class was generated from the following files:
include/ThreadPool.h
src/utl/ThreadPool.cpp