ATMI++: atmi::TField< string > Class Template Reference
atmi::TField< string > Class Template Reference
#include <Buffers.h>
Public Member Functions
TField (FLDID32 fid)
TField (const char *n)
virtual ~TField ()
virtual FLDLEN32 length ()
virtual FLDLEN32 size ()
const char * c_str () const
string & operator+= (const string &str)
string & operator+= (const char *s)
string & operator+= (char c)
const char & operator[] (size_t pos) const
char & operator[] (size_t pos)
virtual TField< string > & operator= (const char *s)
virtual TField< string > & operator= (const string &str)
virtual TField< string > & operator= (char &c)
operator string ()
Public Member Functions inherited from atmi::Field
virtual ~Field ()
int type ()
const char * tname ()
FLDID32 id ()
int number ()
const char * name ()
FLDOCC32 occurence ()
int error ()
virtual long needed ()
const char * what ()
Protected Member Functions
virtual int set (Buffer *b)
virtual int add (Buffer *b)
virtual int get (Buffer *b)
virtual int get (Buffer *b, FLDOCC32 occ)
Protected Member Functions inherited from atmi::Field
int handleFerror (int, const char *,...)
virtual void setFocc (FLDOCC32 occ)
virtual void setup (FLDID32 fid)
virtual int remove (Buffer *b)
Protected Attributes
string value
Detailed Description
template<>
class atmi::TField< string >
Specialization of template TField which handles string typed fields.
This class is using a string object to hold and handle string data
Constructor & Destructor Documentation
atmi::TField< string >::TField (FLDID32 fid) inline
Constructs a TField for the passed field id
The search is done in the tables identified by FLDTBLDIR32 and FIELDTBLS32
Parameters
fid the fml field id to setup (as defined in the FML tables)
atmi::TField< string >::TField (const char * n) inline
Constructs a TField for the passed name
The search is done in the tables identified by FLDTBLDIR32 and FIELDTBLS32
Parameters
n the fml field name to setup (as defined in the FML tables)
virtual atmi::TField< string >::~TField () inline virtual
Member Function Documentation
virtual int atmi::TField< string >::add (Buffer * b) inline protected virtual
add the fiels into the buffer
When successfull the value of focc is set
Parameters
b buffer in which to add the field.
Implements atmi::Field.
References atmi::Buffer::extend(), atmi::Buffer::get_buffer(), atmi::Buffer::occurences(), atmi::Buffer::size(), atmi::Buffer::used(), and atmi::BufferException::what().
const char* atmi::TField< string >::c_str () const inline
Returns
a C string (with \0) of current string's content.
virtual int atmi::TField< string >::get (Buffer * b) inline protected virtual
Retrieves the value of the field found into the buffer
Parameters
b buffer from which to retrieve the field's value
Implements atmi::Field.
virtual int atmi::TField< string >::get (Buffer * b, FLDOCC32 occ) inline protected virtual
Retrieves the value of the field's occurence found into the buffer
Upon success the value of focc is set to the retrieved occurence.
Parameters
b buffer from which to retrieve the field's value
occ occurence to retreive
Implements atmi::Field.
References atmi::Buffer::get_buffer().
virtual FLDLEN32 atmi::TField< string >::length () inline virtual
Returns
the string's length
Implements atmi::Field.
atmi::TField< string >::operator string () inline
casts the field value
string& atmi::TField< string >::operator+= (const string & str) inline
Appends a copy of the argument to the string.
The new string content is the content existing in the string object before the call followed by the content of the argument.
The append member function provides a similar functionality with additional options.
Parameters
str a copy of the content of this object is appended to the object's content.
Returns
*this
string& atmi::TField< string >::operator+= (const char * s) inline
Appends a copy of the argument to the string.
The new string content is the content existing in the string object before the call followed by the content of the argument.
The append member function provides a similar functionality with additional options.
Parameters
s a pointer to an array containing a null-terminated character sequence (C string), which is appended to the object's content.
Returns
*this
string& atmi::TField< string >::operator+= (char c) inline
Appends a copy of the argument to the string.
The new string content is the content existing in the string object before the call followed by the content of the argument.
The append member function provides a similar functionality with additional options.
Parameters
c character. This single character is appended to the string object's content.
Returns
*this
virtual TField<string>& atmi::TField< string >::operator= (const char * s) inline virtual
string& operator= (char c);
String assignment Sets a copy of the argument as the new content for the string object.
The previous content is dropped.
The assign member function provides a similar functionality with additional options.
Parameters
s a pointer to an array containing a null-terminated character sequence (C string), which is copied as the new content for the object.
virtual TField<string>& atmi::TField< string >::operator= (const string & str) inline virtual
string& operator= (char c);
String assignment Sets a copy of the argument as the new content for the string object.
The previous content is dropped.
The assign member function provides a similar functionality with additional options.
Parameters
str a copy of the content of this object is used as the new content for the object.
Reimplemented from atmi::Field.
virtual TField<string>& atmi::TField< string >::operator= (char & c) inline virtual
String assignment Sets a copy of the argument as the new content for the string object.
The previous content is dropped.
The assign member function provides a similar functionality with additional options.
Parameters
c the content is set to a single character.
const char& atmi::TField< string >::operator[] (size_t pos) const inline
Returns a reference the character at position pos in the string.
The function actually returns data()[ pos ].
The at member function has the same behavior as this operator function, except that at also performs a range check.
Parameters
pos position within the string of the character to be retrieved. Notice that the first character in the string has a position of 0, not 1. size_t is an unsigned integral type.
Returns
The character at the specified position in the string.
char& atmi::TField< string >::operator[] (size_t pos) inline
Returns a reference the character at position pos in the string.
The function actually returns data()[ pos ].
The at member function has the same behavior as this operator function, except that at also performs a range check.
Parameters
pos position within the string of the character to be retrieved. Notice that the first character in the string has a position of 0, not 1. size_t is an unsigned integral type.
Returns
The character at the specified position in the string.
virtual int atmi::TField< string >::set (Buffer * b) inline protected virtual
Returns
a null terminated const char * operator const char*() {
return value.c_str(); };
Implements atmi::Field.
References atmi::Buffer::get_buffer().
virtual FLDLEN32 atmi::TField< string >::size () inline virtual
Returns
the string's size
Member Data Documentation
string atmi::TField< string >::value protected
The documentation for this class was generated from the following file:
include/Buffers.h