ATMI++: atmi::BufferException Class Reference
atmi::BufferException Class Reference
#include <Exceptions.h>
Public Member Functions
BufferException (int err, const char *msg=NULL,...) throw ()
int getFerror ()
virtual const char * getFmlerrmsg ()
virtual const char * getMessage ()
virtual const char * what () throw ()
Public Member Functions inherited from atmi::Exception
Exception (const char *msg=NULL,...) throw ()
virtual ~Exception () throw ()
void setup_message (const char *, va_list)
Protected Attributes
int ferror
Protected Attributes inherited from atmi::Exception
string message
Constructor & Destructor Documentation
atmi::BufferException::BufferException (int err, const char * msg = NULL, ...) throw ()
Member Function Documentation
int atmi::BufferException::getFerror ()
Returns
tuxedo FML error number
const char * atmi::BufferException::getFmlerrmsg () virtual
Returns
tuxedo FML error message string
const char * atmi::BufferException::getMessage () virtual
Returns
error message.
const char * atmi::BufferException::what () throw () virtual
Returns
user friendly text message
Reimplemented from atmi::Exception.
Referenced by atmi::TField< T >::add(), atmi::TField< string >::add(), and atmi::TField< char * >::add().
Member Data Documentation
int atmi::BufferException::ferror protected
The documentation for this class was generated from the following files:
include/Exceptions.h
src/tuxedo/BufferException.cpp