ATMI++: atmi::Exception Class Reference
atmi::Exception Class Reference
#include <Exceptions.h>
Public Member Functions
Exception (const char *msg=NULL,...) throw ()
virtual ~Exception () throw ()
virtual const char * what () throw ()
void setup_message (const char *, va_list)
Protected Attributes
string message
Detailed Description
Base class of ATMI++ exception
Can be used to throw any kind of error message in a consitent way.
Constructor & Destructor Documentation
atmi::Exception::Exception (const char * msg = NULL, ...) throw ()
create a new instance
Parameters
msg error message
virtual atmi::Exception::~Exception () throw () inline virtual
Member Function Documentation
void atmi::Exception::setup_message (const char * msg, va_list args)
helper to build string message using va_list.
Message length is limited to 1024 characters long.
Referenced by atmi::Queue::handleDiagnostics(), atmi::Tuxedo::handleTperrno(), atmi::InterruptException::InterruptException(), and atmi::TimeoutException::TimeoutException().
const char * atmi::Exception::what () throw () virtual
Returns
user friendly text message
Reimplemented in atmi::DiagnosticException, atmi::TuxedoException, atmi::BufferException, atmi::UnixException, and atmi::UnixException.
Member Data Documentation
string atmi::Exception::message protected
The documentation for this class was generated from the following files:
include/Exceptions.h
src/tuxedo/Exception.cpp