ATMI++: atmi::TField< T > Class Template Reference
atmi::TField< T > Class Template Reference
#include <Buffers.h>
Public Member Functions
TField (FLDID32 fid)
TField (const char *n)
virtual ~TField ()
virtual FLDLEN32 length ()
T operator= (T v)
operator T ()
Public Member Functions inherited from atmi::Field
virtual ~Field ()
int type ()
const char * tname ()
FLDID32 id ()
int number ()
const char * name ()
FLDOCC32 occurence ()
int error ()
virtual long needed ()
const char * what ()
virtual Field & operator= (const string &)
Protected Member Functions
virtual int set (Buffer *b)
virtual int add (Buffer *b)
virtual int get (Buffer *b)
virtual int get (Buffer *b, FLDOCC32 occ)
Protected Member Functions inherited from atmi::Field
int handleFerror (int, const char *,...)
virtual void setFocc (FLDOCC32 occ)
virtual void setup (FLDID32 fid)
virtual int remove (Buffer *b)
Protected Attributes
T value
Detailed Description
template<class T>
class atmi::TField< T >
Template that handles non pointer data types (short, long, char, double, ...)
Constructor & Destructor Documentation
template<class T > atmi::TField< T >::TField (FLDID32 fid) inline
Constructs a TField for the passed field id
The search is done in the tables identified by FLDTBLDIR32 and FIELDTBLS32
Parameters
fid the fml field id to setup (as defined in the FML tables)
This array is used to check that FML type matches template TField's type
template<class T > atmi::TField< T >::TField (const char * n) inline
Constructs a TField for the passed name
The search is done in the tables identified by FLDTBLDIR32 and FIELDTBLS32
Parameters
n the fml field name to setup (as defined in the FML tables)
template<class T > virtual atmi::TField< T >::~TField () inline virtual
Member Function Documentation
template<class T > virtual int atmi::TField< T >::add (Buffer * b) inline protected virtual
add the fiels into the buffer
When successfull the value of focc is set
Parameters
b buffer in which to add the field.
Implements atmi::Field.
References atmi::Buffer::extend(), atmi::Buffer::get_buffer(), atmi::Buffer::occurences(), atmi::Buffer::size(), atmi::Buffer::used(), and atmi::BufferException::what().
template<class T > virtual int atmi::TField< T >::get (Buffer * b) inline protected virtual
Retrieves the value of the field found into the buffer
Parameters
b buffer from which to retrieve the field's value
Implements atmi::Field.
template<class T > virtual int atmi::TField< T >::get (Buffer * b, FLDOCC32 occ) inline protected virtual
Retrieves the value of the field's occurence found into the buffer
Upon success the value of focc is set to the retrieved occurence.
Parameters
b buffer from which to retrieve the field's value
occ occurence to retreive
Implements atmi::Field.
References atmi::Buffer::get_buffer().
template<class T > virtual FLDLEN32 atmi::TField< T >::length () inline virtual
Returns
de length (or size) of the field's data
Implements atmi::Field.
template<class T > atmi::TField< T >::operator T () inline
casts the field value ... TField<int> f (fid); f = 156 ; int x = f ; // returns 156 ...
template<class T > T atmi::TField< T >::operator= (T v) inline
Assigns a value to the field ... TField<int> f (fid); f = 156 ; // Set value to 156 ...
template<class T > virtual int atmi::TField< T >::set (Buffer * b) inline protected virtual
set the value of the field's value
Parameters
b the buffer in which the value must be changed
Implements atmi::Field.
References atmi::Buffer::get_buffer().
Member Data Documentation
template<class T > T atmi::TField< T >::value protected
The documentation for this class was generated from the following file:
include/Buffers.h