ATMI++: atmi::Logger Class Reference
atmi::Logger Class Reference
#include <Logger.h>
Public Member Functions
virtual void error (const char *msg,...)
virtual void warning (const char *msg,...)
virtual void info (const char *msg,...)
virtual void finer (const char *msg,...)
virtual void debug (int indent, const char *msg,...)
void set_log_level (LoggingLevel level)
void set_log_level (int level)
int get_log_level ()
Protected Member Functions
virtual void log (LoggingLevel at, const char *msg, va_list args)
void setup_level_names ()
Protected Attributes
string LEVELS [5]
int level
Detailed Description
Interface og the logging facility
Verbose is the DEBUG log level (level value 0) and least verbose is ERROR (level value 4). Write messages that matches the current level value and above.
Member Function Documentation
void atmi::Logger::debug (int indent, const char * msg, ...) virtual
Write a debug message
Parameters
indent indentation level
msg message string
... insertion values
References atmi::DEBUG, and log().
void atmi::Logger::error (const char * msg, ...) virtual
Write an error message
Parameters
msg message string
... insertion values
References atmi::ERROR, and log().
void atmi::Logger::finer (const char * msg, ...) virtual
Write a finer message
Parameters
msg message string
... insertion values
References atmi::FINER, and log().
int atmi::Logger::get_log_level ()
Returns
current logging level
References level.
void atmi::Logger::info (const char * msg, ...) virtual
Write an info message
Parameters
msg message string
... insertion values
References atmi::INFO, and log().
virtual void atmi::Logger::log (LoggingLevel at, const char * msg, va_list args) inline protected virtual
Overide this method to implement output handling.
Parameters
at the level to which this message correspond's
msg message to log
args substitution arguments of the message.
Reimplemented in atmi::ULOGLogger, and atmi::StandardLogger.
Referenced by debug(), error(), finer(), info(), and warning().
void atmi::Logger::set_log_level (LoggingLevel level)
Set a new logging level
Parameters
level level from which the logger starts to write messages
References level.
void atmi::Logger::set_log_level (int level)
Set a new logging level
Parameters
level level from which the logger starts to write messages
References level.
void atmi::Logger::setup_level_names () protected
Setup the logging level name array
References LEVELS.
void atmi::Logger::warning (const char * msg, ...) virtual
Write a warning message
Parameters
msg message string
... insertion values
References log(), and atmi::WARNING.
Member Data Documentation
int atmi::Logger::level protected
Referenced by get_log_level(), and set_log_level().
string atmi::Logger::LEVELS[5] protected
Referenced by setup_level_names().
The documentation for this class was generated from the following files:
include/Logger.h
src/tuxedo/Logger.cpp