ATMI++: atmi::Tp Class Reference
atmi::Tp Class Reference
#include <Tuxedo.h>
Public Member Functions
int call (char *idata, long ilen, char **odata, long *olen, int *urcode=NULL, int retries=0, int delay=0)
int call (Buffer *buffer, int *urcode=NULL, int retries=0, int delay=0)
int call (char **idata=NULL, long *ilen=0, int *urcode=NULL, int retries=0, int delay=0)
int acall (char *idata=NULL, long ilen=0)
int reply (char **data, long *len, int *urcode=NULL, int *cd=NULL)
int acall (Buffer *buffer)
int reply (Buffer *buffer, int *urcode=NULL, int *cd=NULL)
int cancel (int cd=0)
int getCallDesc ()
string getService ()
Tp (const char *service)
Public Member Functions inherited from atmi::Tuxedo
Tuxedo ()
virtual ~Tuxedo ()
char * allocate (const char *type, const char *subtype, long size)
char * extend (char *buffer, long extent)
void free (char *buffer)
int begin (int timeout=0)
int commit ()
int abort ()
long get_errno ()
const char * get_errmsg ()
int get_errnodetail ()
const char * get_errdetail ()
void set_context (TPCONTEXT_T c)
TPCONTEXT_T get_context ()
long get_flags ()
void set_flags (long flags)
void reset_flags (long flags)
void unsetFlags (long flags)
Additional Inherited Members
Static Public Member Functions inherited from atmi::Tuxedo
static const char * version ()
Static Public Attributes inherited from atmi::Tuxedo
static const long FAILED = -1
Protected Member Functions inherited from atmi::Tuxedo
void switch_context ()
void updateErrno ()
virtual int handleTperrno (int tpe, const char *msg=NULL,...)
Static Protected Member Functions inherited from atmi::Tuxedo
static long unset (long, long)
static long set (long, long)
Protected Attributes inherited from atmi::Tuxedo
long flags
nl_catd catd
Detailed Description
Implement TP calls
Constructor & Destructor Documentation
atmi::Tp::Tp (const char * service)
Parameters
service service name (< 32 characters long)
Member Function Documentation
int atmi::Tp::acall (char * idata = NULL, long ilen = 0)
acall() sends a request message to the service named by svc.
Parameters: idata - a data buffer preveously allocated with tpalloc() and hols input data ilen - idata buffer lenght.
Returns
call descriptor if call succeeded else -1
Exceptions
An exception is raised upon failure
int atmi::Tp::acall (Buffer * buffer)
acall() sends a request message to the service named by svc.
Parameters: buffer - a fielded buffer preveously allocated with tpalloc() and hols input data
Returns
call descriptor if call succeeded else -1
Exceptions
An exception is raised upon failure
References atmi::Buffer::get_buffer(), and atmi::Buffer::size().
int atmi::Tp::call (char * idata, long ilen, char ** odata, long * olen, int * urcode = NULL, int retries = 0, int delay = 0)
call() sends a request and synchronously awaits its reply. A call to call () returns 0 if call succeed, -1 when no urcode was found else urcode is returned and should be > 0. All other error conditions are handled through Exceptions.
Parameters
idata a data buffer preveously allocated with tpalloc() and hols input data
ilen idata buffer lenght.
odata a data buffer preveously allocated with tpalloc() and that will hold returned data by the called service.
olen reponse buffer length.
urcode user return code (see tpreturn)
retries call is attempted at most retries times.
delay delay in seconds between each retry.
Returns
tpurcode if TPESVCFAIL a user returned code (tpurcode) > 0
-1 is retuened upon service failure TPFAIL and tpurcode == 0
0 TPSUCCESS is returned
Exceptions
ServiceException Upon TPESVCERR.
TimeoutException Upon TPETIME.
TuxedoException thrown for the other error conditions.
int atmi::Tp::call (Buffer * buffer, int * urcode = NULL, int retries = 0, int delay = 0)
call() sends a request and synchronously awaits its reply. A call to call () returns 0 if call succeed, -1 when no urcode was found else urcode is returned and should be > 0. All other error conditions are handled through Exceptions.
Parameters
buffer a data buffer preveously allocated
urcode user return code (see tpreturn)
retries call is attempted at most retries times.
delay delay in seconds between each retry.
Returns
tpurcode if TPESVCFAIL a user returned code (tpurcode) > 0
-1 is retuened upon service failure TPFAIL and tpurcode == 0
0 TPSUCCESS is returned
Exceptions
ServiceException Upon TPESVCERR.
TimeoutException Upon TPETIME.
TuxedoException thrown for the other error conditions.
References atmi::Buffer::get_buffer(), atmi::Buffer::set_buffer(), and atmi::Buffer::size().
int atmi::Tp::call (char ** idata = NULL, long * ilen = 0, int * urcode = NULL, int retries = 0, int delay = 0)
call() sends a request and synchronously awaits its reply. A call to call () returns 0 if call succeed, -1 when no urcode was found else urcode is returned and should be > 0. All other error conditions are handled through Exceptions.
Input data buffer is used to as output data buffer.
Parameters
idata a data buffer preveously allocated with tpalloc() and holds input data
ilen idata buffer lenght.
urcode user return code (see tpreturn)
retries call is attempted at most retries times.
delay delay in seconds between each retry.
Returns
tpurcode if TPESVCFAIL a user returned code (tpurcode) > 0
-1 is retuened upon service failure TPFAIL and tpurcode == 0
0 TPSUCCESS is returned
Exceptions
ServiceException Upon TPESVCERR.
TimeoutException Upon TPETIME.
TuxedoException thrown for the other error conditions.
int atmi::Tp::cancel (int cd = 0)
Cancel acall.
Parameters
cd - a call descriptor. if 0 then last acall descriptor is used.
int atmi::Tp::getCallDesc () inline
string atmi::Tp::getService () inline
int atmi::Tp::reply (char ** data, long * len, int * urcode = NULL, int * cd = NULL)
get reply from preveous acall().
Parameters
data - a data buffer preveously allocated with tpalloc() and that will hold returned data by the called service.
urcode - user return code
len - reponse buffer length.
cd - a call descriptor. if 0 then last acall descriptor is used.
int atmi::Tp::reply (Buffer * buffer, int * urcode = NULL, int * cd = NULL)
get reply from preveous acall().
Parameters
buffer - a fielded buffer preveously allocated with tpalloc() and that will hold returned data by the called service.
urcode - user return code
cd - a call descriptor. if 0 then last acall descriptor is used.
References atmi::Buffer::get_buffer(), atmi::Buffer::set_buffer(), and atmi::Buffer::size().
The documentation for this class was generated from the following files:
include/Tuxedo.h
src/tuxedo/Tp.cpp