ATMI++: atmi::TField< char * > Class Template Reference
atmi::TField< char * > Class Template Reference
#include <Buffers.h>
Public Member Functions
TField (FLDID32 fid)
TField (const char *n)
virtual ~TField ()
virtual FLDLEN32 length ()
void setCarray (const char *c, long s)
virtual void getCarray (char *carray, long size)
TField< char * > & operator= (TField< char * > &carray)
Public Member Functions inherited from atmi::Field
virtual ~Field ()
int type ()
const char * tname ()
FLDID32 id ()
int number ()
const char * name ()
FLDOCC32 occurence ()
int error ()
virtual long needed ()
const char * what ()
virtual Field & operator= (const string &)
Protected Member Functions
virtual int set (Buffer *b)
virtual int add (Buffer *b)
virtual int get (Buffer *b)
virtual int get (Buffer *b, FLDOCC32 occ)
Protected Member Functions inherited from atmi::Field
int handleFerror (int, const char *,...)
virtual void setFocc (FLDOCC32 occ)
virtual void setup (FLDID32 fid)
virtual int remove (Buffer *b)
Protected Attributes
FLDLEN32 len
char * value
Detailed Description
template<>
class atmi::TField< char * >
Specialization of template TField which handles CARRAY typed fields.
This class is using a string object to hold and handle char * data
Constructor & Destructor Documentation
atmi::TField< char * >::TField (FLDID32 fid) inline
Constructs a TField for the passed field id
The search is done in the tables identified by FLDTBLDIR32 and FIELDTBLS32
Parameters
fid the fml field id to setup (as defined in the FML tables)
atmi::TField< char * >::TField (const char * n) inline
Constructs a TField for the passed name
The search is done in the tables identified by FLDTBLDIR32 and FIELDTBLS32
Parameters
n the fml field name to setup (as defined in the FML tables)
virtual atmi::TField< char * >::~TField () inline virtual
Member Function Documentation
virtual int atmi::TField< char * >::add (Buffer * b) inline protected virtual
add the fiels into the buffer
When successfull the value of focc is set
Parameters
b buffer in which to add the field.
Implements atmi::Field.
References atmi::Buffer::extend(), atmi::Buffer::get_buffer(), atmi::Buffer::occurences(), atmi::Buffer::size(), atmi::Buffer::used(), and atmi::BufferException::what().
virtual int atmi::TField< char * >::get (Buffer * b) inline protected virtual
Retrieves the value of the field found into the buffer
Parameters
b buffer from which to retrieve the field's value
Implements atmi::Field.
virtual int atmi::TField< char * >::get (Buffer * b, FLDOCC32 occ) inline protected virtual
Retrieves the value of the field's occurence found into the buffer
Upon success the value of focc is set to the retrieved occurence.
Parameters
b buffer from which to retrieve the field's value
occ occurence to retreive
Implements atmi::Field.
References atmi::Buffer::get_buffer().
virtual void atmi::TField< char * >::getCarray (char * carray, long size) inline virtual
Returns
new allocated pointer to the value of the carray virtual ACarray getCarrayAlloc () {
 Carray carray = new char[length()];
 memcpy ( carray, value, length () );
return new ACarray (&carray); }; copy (memcpy) the field's value into carray. If size is smaller than the length of the field, then only size characters are copied. If size is bigger then the field's length, then length characters are copied.
Parameters
carray pointer to a character buffer
size size of the buffer
virtual FLDLEN32 atmi::TField< char * >::length () inline virtual
Returns
returns the size of the carray
Implements atmi::Field.
TField<char *>& atmi::TField< char * >::operator= (TField< char * > & carray) inline
copy the field's value
References len, and value.
virtual int atmi::TField< char * >::set (Buffer * b) inline protected virtual
set the value of the field's value
Parameters
b the buffer in which the value must be changed
Implements atmi::Field.
References atmi::Buffer::get_buffer().
void atmi::TField< char * >::setCarray (const char * c, long s) inline
Assigns a value to the field
Member Data Documentation
FLDLEN32 atmi::TField< char * >::len protected
Referenced by operator=().
char* atmi::TField< char * >::value protected
Referenced by operator=().
The documentation for this class was generated from the following file:
include/Buffers.h