ATMI++: atmi Namespace Reference
atmi Namespace Reference
Classes
class AbortedException
class AbstractClient
class AbstractServer
class Barrier
class BlockingException
class Buffer
class BufferException
class ClientSocket
class ConcurrencyException
class Condition
class DiagnosticException
class Event
class Exception
class Field
class InterruptException
class Logger
class Mutex
class NomsgException
class Pipe
class Queue
class QueueStream
class Runnable
class ScopedMutex
class ServerSocket
class ServiceException
class Socket
class StandardLogger
class TestJob
class TField
class TField< char * >
class TField< string >
class Thread
class ThreadPool
class TimeoutException
class Tp
class Tuxedo
class TuxedoException
class ULOGLogger
class UnixException
class Worker
class YamlConfig
class YamlException
Typedefs
typedef char * Carray
typedef auto_ptr< Carray > ACarray
typedef auto_ptr< Buffer > ABuffer
typedef auto_ptr< Logger > ALogger
typedef auto_ptr< Tp > ATp
typedef auto_ptr< Queue > AQueue
typedef auto_ptr< YamlConfig > AYamlConfig
typedef enum
atmi::yaml_node_types_e yaml_node_types_t
Enumerations
enum LoggingLevel {
ERROR =4, WARNING =3, INFO =2, FINER =1,
DEBUG =0
}
enum yaml_node_types_e { YAML_NODE, YAML_LEAF, YAML_SEQ_LEAF }
Functions
ostream & operator<< (ostream &o, TField< string > &f)
ostream & operator<< (ostream &out, QueueStream &qs)
istream & operator>> (istream &in, QueueStream &qs)
void * ThreadStartup (void *)
Detailed Description
implementation of Socket class
Typedef Documentation
typedef auto_ptr<Buffer> atmi::ABuffer
typedef auto_ptr<Carray> atmi::ACarray
typedef auto_ptr<Logger> atmi::ALogger
typedef auto_ptr<Queue> atmi::AQueue
typedef auto_ptr<Tp> atmi::ATp
typedef auto_ptr<YamlConfig> atmi::AYamlConfig
typedef char* atmi::Carray
typedef enum atmi::yaml_node_types_e atmi::yaml_node_types_t
Enumeration Type Documentation
enum atmi::LoggingLevel
Enumerator
ERROR
WARNING
INFO
FINER
DEBUG
enum atmi::yaml_node_types_e
Enumerator
YAML_NODE
YAML_LEAF
YAML_SEQ_LEAF
Function Documentation
ostream & atmi::operator<< (ostream & out, QueueStream & qs)
Global utility to stream out the content of a Queue
Parameters
out output stream
qs queue stream that will handle the reading of messages
References atmi::Tuxedo::abort(), atmi::Tuxedo::allocate(), atmi::Tuxedo::begin(), atmi::Tuxedo::commit(), atmi::Queue::dequeue(), and atmi::Tuxedo::free().
ostream & atmi::operator<< (ostream & o, TField< string > & f)
Helper that handles the operator << between output streams and field value
istream & atmi::operator>> (istream & in, QueueStream & qs)
Global utility to stream in a Queue
Parameters
in input stream
qs queue stream that handles the writing of messages to
References atmi::Tuxedo::abort(), atmi::Tuxedo::allocate(), atmi::Tuxedo::begin(), atmi::Tuxedo::commit(), atmi::Queue::enqueue(), atmi::Tuxedo::free(), and atmi::QueueStream::getBuffSize().
void * atmi::ThreadStartup (void * args)
This function is a helper function. It has normal C linkage, and is the base for newly created Thread objects. It runs the run method on the thread object passed to it (as a void *).
References atmi::Thread::destroy_when_ended(), and atmi::Thread::run().
Referenced by atmi::Thread::start().