$set 100 Tuxedo ATMI++ message catalog		
$ number		message
1		L'appel à tpopen() a échoué.
2		L'appel à  tpclose() a échoué.
3		L'appel à tpclose() en fin d'execution d'un thread a échoué.
4		L'appel à tpopen() en fin d'execution d'un thread a échoué.
5		Assignation d'un champs à la valeur NULL !!??
6		Ajout d'une champs avec la valeur NULL !!??
7		La methode append n'est pas encore implémentée !!??
8		La suppression a échouée. Le champs passé référence la valeur NULL !!
9		L'opération get sur le buffer a échouée. Le champs passé référence la valeur NULL !!
10	L'opération get sur le buffer a échouée. Le champs passé référence la valeur NULL !!
11	Récupération du champs a échouée pour %s (%d).
12	L'appel à Fchksum sur le buffer a échouée.
13	Copie de buffer a échouée.
14	Type de champs no supporté %d."
15	Impossible d'estimer la taille de buffer necessaire pour le champs %s (id: %d, occ:%d). Assurez-vous que le champs contient des données.
16	La suppression du champs %s (id: %d, occ: %d) a échouée.
17	Le champs %d n'a pas pu être initialisé. Vérifier la valeur des variable d'environnement Unix FIELDTBLS32 et FLDTBLDIR32.
18	La valeur qspace ou queue n'est pas admissible.
19	Enqueue a échoué, les propriétés qspace et queue n'ont pas été positionnées !!??
20	Dequeue a échoué, les propriétés qspace et queue n'ont pas été positionnées !!??
21	Numéro de diagnostique %d inconnu (tperrno: %d) !!??
22	Methode pas encore implémentée.
23	La valeur QoS n'est pas connue.
24	QueueStream a besoin que la propriété queue soit valorisée. La valeur trouvée est NULL.
25	L'export a échoué. Verifiez la taille de buffer demandé (par exemple %d bytes).
26	L'import a échoué. Ce message a-t-il été export à l'aide tpexport ?
27	Nom de service '%s' trop long.
28	L'allocation d'un buffer a échouée. Consultez la ULOG pour plus d'info..
29	La réallocation du buffer a échouée. Consultez la ULOG pour plus d'info..
30	Impossible de démarrer la transaction. Consultez la ULOG pour plus d'info..
31	Commit de la transaction a échoué. Consultez la ULOG pour plus d'info..
32	Abort de la transaction a échoué. Consultez la ULOG pour plus d'info..
33	Numéro d'erreur %d inconnu.
34	Switch de context Tuxedo impossible. L'appel à tpgetctxt a échoué ( contexte cible %d ).
35	Switch de context Tuxedo impossible ( contexte cible %d ).
36	QueueStream a besoin que la propriété queue soit valorisée. La valeur trouvée est NULL.
37	L'export a échoué. Verifiez la taille de buffer demandé (par exemple %d bytes).
38	L'import a échoué. Ce message a-t-il été export à l'aide tpexport ?
39	Impossible de se raccorder au DOMAIN Tuxedo. Le domain est-il lancé ? Vérifiez si la variable TUXCONFIG a bien été positionnée.
40  Enqueue a échoué, les propriétés qspa replyqueue (NULL) n'a pas été positionnées !!??
