$set 100 Tuxedo ATMI++ message catalog		
$ number		message
1		Call to tpopen() failed.
2		Call to tpclose() failed.
3		Thread done call to tpclose() failed.
4		Thread init call to tpopen() failed.
5		Setting a NULL field !!??
6		Adding a NULL field !!??
7		Method append is not implemented yat !!??
8		Remove failed. You passed a NULL pointer as field !!
9		Buffer get failed. You passed a NULL pointer as field !!
10	Buffer get failed. You passed a NULL pointer as field !!
11	Get field occurences in buffer failed for %s (%d).
12	Fchksum call on buffer failed.
13	FCOPY32 failed.
14	Unsupported field type %d."
15	FNEEDED32 failed to estimate needed space for field %s (id: %d, occ:%d). Make sure field contains data (length() > 0).
16	FDEL32 failed for field %s (id: %d, occ: %d) failed.
17	Failed to initialize field %d. Check the values of FIELDTBLS32 and FLDTBLDIR32 and make sure you have read permission on the FML tables files.
18	Invalid values for qspace or queue parameter
19	Enqueue failed, qspace and queue properties have not been set !!??
20	Dequeue failed, qspace and queue properties have not been set !!??
21	Never heard about this diagno %d (tperrno: %d) !!??
22	Not implemented yet.
23	Unsupported QoS for queu operations.
24	QueueStream needs a queue to by initialized. Passed queue was NULL.
25	TPEXPORT failed. Check buffer size (how about %d bytes).
26	TPIMPORT failed. Was this message exported using tpexport ?
27	Given service name '%s' is too long.
28	TPALLOCATE failed. Check ULOG for more information.
29	TPREALLOC failed. Check ULOG for more information.
30	TPBEGIN failed. Check ULOG for more information.
31	TPCOMMIT failed. Check ULOG for more information.
32	TPABORT failed. Check ULOG for more information.
33	Never heard about this tperrno (%d).
34	Context switch failed while calling tpgetctxt ( target context was %d ).
35	Context switch failed ( target context was %d ).
36	QueueStream needs a queue to by initialized. Passed queue was NULL.
37	TPEXPORT failed. Check buffer size (last buffer size was %d bytes).
38	TPIMPORT failed. Was this message exported using tpexport ?
39	Failed to join DOMAIN. Is DOMAIN started ? Check TUXCONFIG env var and ULOG for more.
40	Enqueue failed, replyqueue (NULL) properties have not been set !!??
